---
  - name: find yum/dnf config
    stat: "path={{ item }}"
    register: packager_conf_stat
    with_items:
      - /etc/yum.conf
      - /etc/dnf/dnf.conf

  - name: prevent yum/dnf from updating kernel if kernel_to_use is specific
    lineinfile:
      dest: "{{ item.stat.path }}"
      regexp: "^exclude"
      line: "exclude=kernel"
      insertafter: "^\\[main\\]"
      state: present
    when:
      - kernel_type in ["realtime", "specific"] and item.stat.isreg is defined and item.stat.isreg
    with_items: "{{ packager_conf_stat.results }}"

  - name: enable yum/dnf kernelupdating if kernel_to_use is not specific
    lineinfile:
      dest: "{{ item.stat.path }}"
      regexp: "^exclude"
      state: absent
    when:
      - kernel_type not in ["realtime", "specific"] and item.stat.isreg is defined and item.stat.isreg
    with_items: "{{ packager_conf_stat.results }}"

