---
  - name: make sure linux-headers is installed for the kernel version are currently running
    action: "{{ ansible_pkg_mgr }} name=linux-headers-{{ ansible_kernel }} state=present"
    when: kernel_type == "inbox" or (kernel_type == "specific" and kernel_data.kernel_version == ansible_kernel)

  - name: fetch all kernel packages
    # no quotes we need word splitting on kernel_urls
    command: apt-get download {{ kernel_urls[ansible_distribution]|join (' ') }}
    args:
      chdir: "{{ kernel_download_dir }}"
    when: (kernel_type == "specific" and kernel_data.kernel_version != ansible_kernel)

  - name: install kernel from downloaded DEBs
    # install dependencies all at once
    shell: dpkg -i {{ kernel_urls[ansible_distribution]|map('regex_replace', '$', '*')|join(' ') }}
    args:
      chdir: "{{ kernel_download_dir }}"
    when: (kernel_type == "specific" and kernel_data.kernel_version != ansible_kernel)

  - name: set grub to boot to specific kernel
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_DEFAULT=.*'
      line: 'GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux {{ kernel_data.kernel_version }}"'
      state: present
    when: (kernel_type == "specific" and kernel_data.kernel_version != ansible_kernel)
    notify:
     - update grub