---
  - name: Update /etc/default/grub file for Ubuntu
    lineinfile:
      dest: /etc/default/grub
      regexp: "GRUB_DEFAULT=0"
      line: "GRUB_DEFAULT=saved"
      state: present
    when: ansible_os_family == "Debian"

  - name: Set Default kernel for Debian OS
    shell: grub-set-default "Advanced options for Ubuntu>Ubuntu, with Linux $(grep "\-rt" /boot/grub/grub.cfg| grep echo | awk {'print $4'}| sed -n 1p)" ; update-grub
    when: ansible_os_family == "Debian"
