---
  - name: Install msr-tools
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
    with_items:
      - msr-tools

  - name: ensure msr kernel module installed
    modprobe: name=msr state=present

  # from kvm_ok script
  - name: Check CPU config 1
    command: "rdmsr --bitfield 0:0 0x3a"
    register: bit_1

  - name: Check CPU config 2
    command: "rdmsr --bitfield 2:2 0x3a"
    register: bit_2

  - fail: msg="Virtualization disabled in BIOS"
    when: "{{ bit_1.stdout.strip() == '1' and bit_2.stdout.strip() == '0' }}"