# Copyright (c) 2017, Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block kolla_deploy_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set kolla_deploy_packages = [
        'gcc',
        'git',
        'libffi-devel',
        'libxml2-devel',
        'libxslt-devel',
        'MariaDB-devel',
        'MariaDB-shared',
        'openssl-devel',
        'python-devel',
        'openssh-clients',
        'sshpass',
        'python-netaddr'
    ] %}

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set kolla_deploy_packages = [
        'build-essential',
        'ca-certificates',
        'git',
        'libffi-dev',
        'libmariadbclient-dev',
        'libssl-dev',
        'libxslt1-dev',
        'python-dev',
        'sshpass',
        'python-netaddr'
    ] %}

{% endif %}

{{ macros.install_packages(kolla_deploy_packages | customizable("packages")) }}

{% block kolla_deploy_install_python_pip %}
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python get-pip.py \
    && rm get-pip.py
{% endblock %}

RUN pip --no-cache-dir install \
    ansible==2.2.0.0 \
    MySQL-python \
    os-client-config \
    pyudev \
    shade

# install kolla deploy source
# create and copy in files as placeholders
ADD kolla-deploy-archive /kolla-deploy-source
RUN ln -s /kolla-deploy-source/* /root/kolla \
    && pip --no-cache-dir install --upgrade /root/kolla \
    && mkdir -p /etc/kolla \
    && cp /root/kolla/etc/kolla/globals.yml /etc/kolla \
    && cp /root/kolla/etc/kolla/passwords.yml /etc/kolla

ENV KOLLA_SERVICE_NAME=kolla-deploy TERM=xterm

CMD ["/bin/sleep", "infinity"]

{% block kolla_deploy_footer %}{% endblock %}
# USER ansible
