# Copyright (c) 2016, Intel Corporation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---

  # the install_kernel role must ensure the kernel headers are installed
  # for distro kernel or for kernel compiled from source

  - set_fact:
      driver_tarball: "{{ item }}"
      driver_name: "{{ item|basename|replace('.tar.gz', '') }}"
    with_fileglob:
      - "*.tar.gz"
    register: driver_info_results

  - set_fact:
      driver_info: "{{ driver_info_results.results|map(attribute='ansible_facts')|list }}"

  - debug: var=driver_info
  - debug: var=target_kernel_version

  - name: extract driver tarball
    unarchive: "src={{ item.driver_tarball }} dest={{ remote_build_dir }} copy=yes"
    with_items: "{{ driver_info }}"

  - name: build driver for specific kernel
    shell: "make clean; make install BUILD_KERNEL={{ target_kernel_version }}"
    args:
      chdir: "{{ remote_build_dir }}/{{ item.driver_name }}/src"
    register: driver_built
    with_items: "{{ driver_info }}"

  # load the new driver by rebooting, otherwise we risk disconnects
  # if we reload module used for mgmt iface

  - name: rebuild initramfs
    # we have to use raw to workaround CentOS dracut bug
    # https://bugs.centos.org/view.php?id=8254
    # 0008254: dracut or mkinitrd throws error "cat: write error: Broken pipe" when run from rsh/rlogin session. underlying problem is lsinitrd
    raw: "{{ rebuild_initramfs_command[ansible_os_family] }}"
    when: driver_built|success

