---
  - name: create registry image store path
    file: "path={{ docker_registry_storage_path }} state=directory"

  - name: Start registry container
    docker_container:
      name: registry
      image: registry:2
      state: started
      restart_policy: always
      ports:
        - "{{ docker_registry_port }}:5000"
      volumes:
        - "{{ docker_registry_storage_path }}:/var/lib/registry"
