# Copyright (c) 2016-2017, Intel Corporation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---

# For each distribution there are four types of kernels to select.
# The kernel type is selected with the kernel_to_use variable.
#
# The following options are available:
#     kernel_to_use=inbox (in-box kernel from OS installation)
#     kernel_to use=latest (the latest available kernel, obtained from from yum update, or apt-get update)
#     kernel_to_use=specific (user to determine a specific kernel)
#     kernel_to_use=realtime (user to determine a realtime kernel)
#
# Two types of kernels requirejmore detailed configuration: realtime and specific.
#
# The realtime kernel requires a URL for a git repository and git tag.
# The kernel will be git cloned and compiled from source.
#
#     kernel_to_use: "realtime"
#     kernel_version: "4.1.10-rt10"
#     kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
#
# Specific kernels require a base URL from which to download RPMs or DEBs
#
#     kernel_base_url: "https://kojipkgs.fedoraproject.org//packages/kernel/4.3.3/300.fc23/x86_64"
#     kernel_version: "4.3.3-300.fc23.x86_64"
#     kernel_tag: ""   # kernel_tag is empty for specific kernels
#
# kernel settings
kernel_info:
  Fedora:
    "23":
      kernel_to_use: specific
      specific:
        kernel_base_url: "https://kojipkgs.fedoraproject.org//packages/kernel/4.3.3/300.fc23/x86_64"
        kernel_version: "4.3.3-300.fc23.x86_64"
        kernel_tag: ""
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
  CentOS:
    "7.2.1511":
      kernel_to_use: inbox
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
      specific:
        kernel_base_url: ""
        kernel_version: ""
        kernel_tag: ""
    "7.3.1611":
      kernel_to_use: inbox
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
      specific:
        kernel_base_url: ""
        kernel_version: ""
        kernel_tag: ""
  RedHat:
    "7.3":
      kernel_to_use: inbox
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
      specific:
        kernel_base_url: ""
        kernel_version: ""
        kernel_tag: ""
    "7.2":
      kernel_to_use: inbox
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
      specific:
        kernel_base_url: ""
        kernel_version: ""
        kernel_tag: ""
  Ubuntu:
    "14.04":
      kernel_to_use: specific
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
      specific:
        kernel_base_url: "http://archive.ubuntu.com/ubuntu/pool/main/l/linux"
        kernel_version: "4.2.0-27-generic"
        kernel_tag: ""
    "16.04":
      kernel_to_use: inbox
      realtime:
        kernel_base_url: "https://gerrit.opnfv.org/gerrit/kvmfornfv"
        kernel_version: "4.1.10-rt10"
        kernel_tag: "WW-2015-52"
      specific:
        kernel_base_url: ""
        kernel_version: ""
        kernel_tag: ""

