---
  - name: Include RedHat dependencies
    include: "{{ ansible_os_family }}.yml"

  - name: Install core packages
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
    register: pkg_mgr_results
    retries: "{{ pkg_mgr_retries }}"
    until: pkg_mgr_results|success
    with_items: "{{ install_dependencies }}"
